import ProtectedRoute from '@/components/layout/protectedRoute'
import { ThemeProvider } from '@/components/ui/shared/theme-provider'
import { AuthProvider } from '@/lib/auth'
import QueryProvider from '@/lib/queryClient'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Toaster } from 'sonner'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<QueryProvider>
					<ThemeProvider
						attribute='class'
						defaultTheme='light'
						enableSystem
						disableTransitionOnChange
					>
						<AuthProvider>
							{' '}
							<ProtectedRoute>{children}</ProtectedRoute>
							<Toaster />
						</AuthProvider>
					</ThemeProvider>
				</QueryProvider>
			</body>
		</html>
	)
}
